### ISSUE TITLE
echo prevents from starting session 

### ISSUE THREAD

**Issue by Zydnar** [jdomenechb/reactphp-symfony-server#3]
https://github.com/jdomenechb/reactphp-symfony-server/blob/507977a7a128bb721e16253a021fdd7e4fa58f79/bin/reactphp-server#L54

Creating sessions throws Headers already sent error.

Possible fix - output message using Symfony\Component\Console\Output\ConsoleOutput instead of echo.

**Comment by jdomenechb** [comment]
I agree with your solution. `echo` was just a nasty way to show that the server is running, but of course this could be improved. Thank you for your feedback!
