### ISSUE TITLE
service worker do not have proper mime type

### ISSUE THREAD

**Issue by Zydnar** [jdomenechb/reactphp-symfony-server#4]
For some reasons fetching service worker is different and also fetching assets via ServiceWorker - browser returns error mime type not specified. Possible fix: rewrite header Content-Type for known extensions eg. from here: [http://svn.apache.org/repos/asf/httpd/httpd/trunk/docs/conf/mime.types](http://svn.apache.org/repos/asf/httpd/httpd/trunk/docs/conf/mime.types )

**Comment by jdomenechb** [comment]
First of all, thank you for your feedback :smile: 

The library focuses on serving requests via Symfony. In that case, the library takes all the headers from the Symfony Response and gives them to ReactPHP. Looking at the error that you get, my first guess would be that Symfony is not is returning a Content-Type header in the response. 

I have checked the following on a brand new Symfony installation:
```
public function health(): Response
{
    $response = new Response();
    $response->setStatusCode(Response::HTTP_OK);

    return $response;
}
```

And performing a request against that action returns a `Content-Type: text/html; charset=UTF-8` header in the response, which is as far as I understand, correct. 

If that explanation does not solve your problem, could you please provide an specific example?

On the other hand, when talking about assets, basic support for assets was added as stated in the FAQ, but it is not the focus of the library. There are many reasons, but the main is that a normal web server, like Nginx or Apache, can deal with assets in a more better way than a ReactPHP implementation. 

For example, they can manage better and more accurate headers for them and serve requests in parallel, something that an standalone PHP process is not able to do yet. Even using a balancer or a ServiceWorker over PHP workers, the performance that you will achieve will be far from the one you would achieve using a webserver.

Despite all this, I consider an improvement could be done on that aspect on the library if really needed. Different developers have different use cases, and of course there might be one in which supporting mime types in the library would solve easily a painful problem. Feel free to give more context if you wish :smile:

**Comment by Zydnar** [comment]
There are no headers set: https://github.com/jdomenechb/reactphp-symfony-server/blob/f85349825a20d5b6f7ae48b69860ed4c27c43ce7/src/Loop/RequestLoop.php#L146
Server worker requests are usually opaque (mode: no-cors) but this is all I know for know. Setting correct Content-Type at this line fixes the problem. Anyway I can provide later more details.

**Comment by jdomenechb** [comment]
Yes, basic support for assets did not implement `Content-Type` header, and your change can fix this. This is what I meant when I said an improvement could be done. However, I had to warn you that the performance you might get for this is far than the desirable.

**Comment by Zydnar** [comment]
Speaking of performance - same line `file_get_contents` - it can kill server handling bigger files. There should be used some stream with header `Transfer-Encoding: chunked` I'm not sure how would chunked reactPHP response look like.

**Comment by jdomenechb** [comment]
I have added the Content-Type header for assets. However, I won't include in this issue what you mentioned about `file_get_contents` and `Transfer-Encoding: chunked`. As I said, support for assets will remain very basic for now, as there are better ways to deal with them. 

I will consider to increase the support in future versions.
