### ISSUE TITLE
Server don't see changes eg. in twig

### ISSUE THREAD

**Issue by Zydnar** [jdomenechb/reactphp-symfony-server#5]
In comparison to regular symfony server refreshing website in browser don't load changes unless of course it's API. In theory watching files like twig is needed only in development.

**Comment by jdomenechb** [comment]
Unfortunately this cannot be implemented at library level. As it is a PHP CLI process running, once one PHP file has been autoloaded in the memory it cannot be replaced nor reloaded until the process exits.

The PHP Symfony server deals with it using the built-in PHP HTTP server, which simulates a full HTTP server and loads/drops all the PHP environment at every request. However, PHP processes keep it in memory while running, and it's the framework's job to deal with every request.

In the company I work with what we do is testing using the Symfony PHP server, and perform the final validation test using the library.

If someone is able to give an insight of how could this be achieved natively, I will consider to reopen the issue.
